### PR TITLE
Implemented methods to create, update and delete scheduled reports

### PR DESCRIPTION
**Pull request by Fensterbank**

### CODE REVIEW

**Comment by Fensterbank** [comment]
Is anybody here or is this repository not maintained anymore?
ping @mattab :-)

**Comment by halfdan** [comment]
@Fensterbank Sorry for the delay. Will give this a review soon!

**Comment by halfdan** [comment]
@JulienMoumne ^

**Comment by julienmoumne** [comment]
Except for the changelog (see https://github.com/Fensterbank/piwik-dotnet-api/commit/458b8ac5e82dd5fbe884ee1c262abc5ba9c4fe6a) it looks very good to me.

**Comment by Fensterbank** [comment]
Thanks for reply.
Oh right, I see my fail with the changelog. :-)

I will commit another update of the changelog.md by prepending the changes of version 0.2 (https://github.com/piwik/piwik-dotnet-api/commit/75afc18471f7382416b90a32a4120ddbe730930f), version 0.3 (https://github.com/piwik/piwik-dotnet-api/commit/82fb3613a3c29ac35c8b3df1e1df0ea7186024e4) and my changes as version 0.4.

Does this meet your expectations or should all these changes be in a version 0.2.
Or should we introduce a third digit where this pull request would have version 0.1.3?

**Comment by julienmoumne** [comment]
All the mentioned changes should be version 0.2 as there was no tag since 0.1 (see https://github.com/piwik/piwik-dotnet-api/releases)

Once you have updated the changelog, I would then :
- merge,
- enable NuGet support,
- tag and publish version 0.2

Thanks for spotting the fact the changelog is not up-to-date and for taking care of it.

**Comment by Fensterbank** [comment]
@JulienMoumne I fixed the changelog now to meet the requirements.

**Comment by julienmoumne** [comment]
Thanks a bunch. 

I will publish the project before end of July. 

See #4

**Comment by Fensterbank** [comment]
You're welcome.
thanks! :+1:

**Pull request merged**
